<?php
// $Id: weblinks_filter.install,v 1.1.2.2 2009/03/05 17:35:20 rmiddle Exp $

/**
 * @file
 * Update Weblinks_filter data.
 */

/**
 * Implementation of hook_update_N().
 * Fix filter naming (http://drupal.org/node/317054).
 */
function weblinks_filter_update_6100() {
  $ret = array();

  $ret[] = update_sql("UPDATE {filters} f SET f.module = 'weblinks_filter' WHERE  f.module = 'weblinks'");

  return $ret;
}
